# Role for using jobs api with default service account
# Handy when using kubernetes API from Python application
{{ if eq .Values.env "prod" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jobs-api
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: create-jobs-role
  namespace: <namespace>
subjects:
  - kind: User
    name: system:serviceaccount:<namespace>:default
    namespace: <namespace>
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: jobs-api
{{ end }}