{{ if eq .Values.env "local" }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-local
  namespace: <namespace>
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: "/mnt/local-cluster-data/mlflow"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: microk8s.io/cluster
              operator: Exists
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-redisai-local
  namespace: redis
  labels:
    type: local-redisai
spec:
  storageClassName: local-storage
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: "/mnt/local-cluster-data/redisai"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: microk8s.io/cluster
              operator: Exists
{{ end }}
