apiVersion: v1
kind: Service
metadata:
  name: serving-loadbalancer-internal
  namespace: <namespace>
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8000
  selector:
    app: serving
