apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017
---
kind: Endpoints
apiVersion: v1
metadata:
  # the name here should match the name of the Service
  name: mongodb
subsets:
  - addresses:
      - ip: {{.Values.mongodb_address}}
    ports:
      - port: 27017