version: "3.9"

services:
  minio:
    container_name: minio
    restart: always  # keep it running
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - /var/gat/minio:/data
    command: minio server /data --console-address ":9001"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.2
    restart: always  # keep it running
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    networks:
      - docker-elk
  kibana:
    image: docker.elastic.co/kibana/kibana:8.3.2
    restart: always  # keep it running
    ports:
      - "5601:5601"
    networks:
      - docker-elk
    depends_on:
      - elasticsearch
  redis:
    image: redis:6.2.3-alpine
    restart: always  # keep it running
    command: redis-server --databases 20
    ports:
      - "6379:6379"

networks:
  docker-elk:
    driver: bridge