apiVersion: batch/v1
kind: Job
metadata:
  name: training-job
spec:
  ttlSecondsAfterFinished: 100
  template:
    metadata:
      name: training-job
    spec:
      nodeSelector:
        cloud.google.com/gke-preemptible: "true"
        cloud.google.com/gke-accelerator: nvidia-tesla-k80
      tolerations:
      - key: cloud.google.com/gke-preemptible
        operator: Equal
        value: "true"
        effect: NoSchedule
      - key: nvidia.com/gpu
        operator: Equal
        value: "present"
        effect: NoSchedule
      containers:
      - name: <model-container-name>
        image: model-image
        env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: <gcp-credentials-path>
          - name: MODEL
            value: model-name
          - name: ENV
            value: <prod/test/local>
        volumeMounts:
          - mountPath: /etc/storage-cred
            name: storage-cred
            readOnly: true
        resources:
          requests:
            cpu: 4
            memory: 8Gi
          limits:
            cpu: 6
            memory: 10Gi
            nvidia.com/gpu: 2 # requesting 2 GPU
      volumes:
        - name: storage-cred
          secret:
            secretName: storage-cred
      restartPolicy: Never # Do not restart containers after they exit